dist: trusty
sudo: required 
language: cpp
os:
- linux
branches:
  only:
  - arduino_library_format_1_5
env:
  global:
    - ARDUINO_IDE_VERSION=1.8.4
install:
  - cd $TRAVIS_BUILD_DIR/ci/travis; ./arduino_ide_install.sh;
  - cd $TRAVIS_BUILD_DIR/ci/travis; ./install_googletest.sh;
  - cd $TRAVIS_BUILD_DIR/ci/travis; ./install_rapidassist.sh;
  - cd $TRAVIS_BUILD_DIR/ci/travis; ./install_win32arduino.sh;
script:
  - cd $TRAVIS_BUILD_DIR/ci/travis; ./build_library.sh;
  - ln -s $TRAVIS_BUILD_DIR/external/BitReader $HOME/Arduino/libraries/.;
  - cd $TRAVIS_BUILD_DIR/ci/travis; ./arduino_build_sketch.sh Basic
  - cd $TRAVIS_BUILD_DIR/ci/travis; ./arduino_build_sketch.sh BlockingWithNonBlocking
  - cd $TRAVIS_BUILD_DIR/ci/travis; ./arduino_build_sketch.sh NonBlockingDemo
  - cd $TRAVIS_BUILD_DIR/ci/travis; ./arduino_build_sketch.sh NonBlockingInterruptedDemo
  - cd $TRAVIS_BUILD_DIR/ci/travis; ./arduino_build_sketch.sh Play10Bits
  - cd $TRAVIS_BUILD_DIR/ci/travis; ./arduino_build_sketch.sh Play16Bits
  - cd $TRAVIS_BUILD_DIR/ci/travis; ./arduino_build_sketch.sh ProgramMemoryRtttl
  - cd $TRAVIS_BUILD_DIR/ci/travis; ./arduino_build_sketch.sh Rtttl2Code
  - cd $TRAVIS_BUILD_DIR/build/bin;
    ./anyrtttl_unittest || true; #do not fail build even if a test fails.
notifications:
  email: true
